#!/bin/bash
# Ask for version
echo "-- MeCms build script --"
echo "Please, enter the version number: "
read version
version="mecms-$version"

# Create build/MeCms
rm -r -f build/MeCms
mkdir -p build/MeCms

# Copy in build/MeCms
cp -a --parents Config/ Console/ Controller/ Locale/ita Model/ Utility/ \
View/ webroot/ COPYNG PERMISSIONS.md README.md version build/MeCms

# Enter build/MeCms
cd build/MeCms

# Remove .directory files
find . -name ".directory" -type f -exec rm -rf {} \;

# Remove old files
find . -name "*.old.*" -type f -exec rm -rf {} \;

# Go back to build/
cd ../

# Create the tar archive
tar -czf $version.tar.gz MeCms/*
echo "The file $version.tar.gz was created"

exit 0