CREATE TABLE IF NOT EXISTS articles (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id INTEGER,
    title VARCHAR(255),
    body TEXT,
    published VARCHAR(1) DEFAULT 'N',
    PRIMARY KEY (id)
)
